# -*- coding: utf-8 -*-
"""johnsnow_dashboard_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vicZLQJzjhqFGvMQrrQsChZ2hKh5Qw9M
"""

# johnsnow_dashboard_app.py
# Simple dashboard for John Snow 1854 cholera data
# Uses: streamlit, folium, streamlit-folium, pandas

import streamlit as st
import pandas as pd
import folium
from folium.plugins import HeatMap
from streamlit_folium import st_folium
from pathlib import Path

# ------------------------------------------------
# 1. Load data
# ------------------------------------------------
def load_data():
    """
    Look for deaths.csv and pumps.csv either in:
    - current folder (.)
    - or in sample_data/   (like in Google Colab)
    """
    for cand in [Path("."), Path("sample_data")]:
        deaths_path = cand / "deaths.csv"
        pumps_path = cand / "pumps.csv"
        if deaths_path.exists() and pumps_path.exists():
            deaths_df = pd.read_csv(deaths_path)
            pumps_df = pd.read_csv(pumps_path)
            return deaths_df, pumps_df

    st.error("Could not find deaths.csv and pumps.csv in '.' or 'sample_data/'.")
    st.stop()


deaths_df, pumps_df = load_data()


# Your column mapping
LAT_COL = "X coordinate"   # ≈ 51.5  (latitude)
LON_COL = "Y coordinate"   # ≈ -0.13 (longitude)

# Standardise column names for easier use
deaths = deaths_df.rename(columns={LAT_COL: "lat", LON_COL: "lon"})
pumps  = pumps_df.rename(columns={LAT_COL: "lat", LON_COL: "lon"})

# ------------------------------------------------
# 2. Streamlit layout
# ------------------------------------------------
st.set_page_config(page_title="John Snow Cholera Dashboard", layout="wide")

st.title("John Snow 1854 Cholera Dashboard")
st.write(
    "Interactive exploration of cholera deaths and pump locations near Broad Street, London."
)

col_left, col_right = st.columns([3, 1], gap="large")

# --- Right column: controls & summary stats ---
with col_right:
    st.subheader("Controls")

    base_tile = st.selectbox(
        "Basemap",
        ["OpenStreetMap", "CartoDB positron", "CartoDB dark_matter", "Stamen TonerLite"],
        index=1,
    )

    show_heat = st.checkbox("Show deaths heatmap", value=True)

    radius = st.slider("Heatmap radius", min_value=5, max_value=30, value=18)

    st.markdown("---")
    st.subheader("Summary")
    st.metric("Number of deaths", len(deaths))
    st.metric("Number of pumps", len(pumps))

# --- Left column: interactive map ---
with col_left:
    center = [deaths["lat"].mean(), deaths["lon"].mean()]

    m = folium.Map(location=center, zoom_start=17, tiles=base_tile)

    # add deaths as blue circle markers
    for _, row in deaths.iterrows():
        folium.CircleMarker(
            location=[row["lat"], row["lon"]],
            radius=3,
            color="blue",
            fill=True,
            fill_opacity=0.4,
        ).add_to(m)

    # add pumps as red markers with labels
    for _, row in pumps.iterrows():
        folium.Marker(
            location=[row["lat"], row["lon"]],
            popup=row.get("Pump Name", "Pump"),
            icon=folium.Icon(color="red", icon="tint", prefix="fa"),
        ).add_to(m)

    # optional heatmap layer for deaths
    if show_heat:
        HeatMap(
            deaths[["lat", "lon"]].values.tolist(),
            radius=radius,
            blur=12,
            min_opacity=0.25,
        ).add_to(m)

    st_data = st_folium(m, height=650, width=None)

st.caption("Zoom and pan to inspect clustering of deaths around the pumps.")


# --- Data Overview ---
st.markdown("### Cholera Death Locations")
st.dataframe(deaths_df.head(10))  # Show only first 10 for clarity

st.markdown("### Pump Locations")
st.dataframe(pumps_df)